### ISSUE TITLE
Compatibility with MRI 2.3

### ISSUE THREAD

**Issue by ch1c0t** [ch1c0t/hobby#1]
Up to this point, I have been testing only against the latest stable MRI. It turned out that on MRI 2.3 the gem is now broken:
```
bundle exec rspec
....F................FF.......

Failures:

  1) Hobby#call when a route was not found responds with 404 status code
     Failure/Error: route = route.dup

     TypeError:
       can't dup NilClass
     # ./lib/hobby/router.rb:19:in `dup'
     # ./lib/hobby/router.rb:19:in `route_for'
     # ./lib/hobby.rb:41:in `block in handle'
     # ./lib/hobby.rb:40:in `catch'
     # ./lib/hobby.rb:40:in `handle'
     # ./lib/hobby.rb:35:in `call'
     # /home/ch1c0t/.gem/gems/rack-test-0.6.3/lib/rack/mock_session.rb:30:in `request'
     # /home/ch1c0t/.gem/gems/rack-test-0.6.3/lib/rack/test.rb:244:in `process_request'
     # /home/ch1c0t/.gem/gems/rack-test-0.6.3/lib/rack/test.rb:58:in `get'
     # ./spec/app_spec.rb:62:in `block (4 levels) in <top (required)>'

  2) Hobby::Router should not find route "/nonexistent"
     Failure/Error: route = route.dup

     TypeError:
       can't dup NilClass
     # ./lib/hobby/router.rb:19:in `dup'
     # ./lib/hobby/router.rb:19:in `route_for'
     # ./spec/router_matchers.rb:18:in `block (2 levels) in <module:RouterMatchers>'
     # ./spec/router_spec.rb:26:in `block (2 levels) in <top (required)>'

  3) Hobby::Router should not find route "/existent/only/for/GET" and "POST"
     Failure/Error: route = route.dup

     TypeError:
       can't dup NilClass
     # ./lib/hobby/router.rb:19:in `dup'
     # ./lib/hobby/router.rb:19:in `route_for'
     # ./spec/router_matchers.rb:18:in `block (2 levels) in <module:RouterMatchers>'
     # ./spec/router_spec.rb:27:in `block (2 levels) in <top (required)>'

Finished in 0.07778 seconds (files took 1.2 seconds to load)
30 examples, 3 failures

Failed examples:

rspec ./spec/app_spec.rb:61 # Hobby#call when a route was not found responds with 404 status code
rspec ./spec/router_spec.rb:26 # Hobby::Router should not find route "/nonexistent"
rspec ./spec/router_spec.rb:27 # Hobby::Router should not find route "/existent/only/for/GET" and "POST"
```
It has been broken since 527cb64d.

It is due to incompatibility between Ruby 2.3 and 2.4. On 2.4 `nil.dup` returns `nil`; on 2.3 -- raises `TypeError`. Related: http://blog.arkency.com/2017/03/prototypes-in-ruby

Before I fix it, I probably should set up Travis or GitLab CI.

**Comment by paneq** [comment]
Good catch!

**Comment by ch1c0t** [comment]
@paneq Thank you for chiming in and for the article. I like a lot your writing style, very informative.

**Comment by paneq** [comment]
Thank you for your kind words. I really appreciate.
